spring.application.name=Clients

# ===============================
# = CONFIGURACIÓN DE BASE DE DATOS H2
# ===============================

spring.datasource.url=jdbc:h2:mem:clientsdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# ===============================
# = CONFIGURACIÓN DE JPA / HIBERNATE
# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ===============================
# = CONSOLA H2
# ===============================

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console